### ISSUE TITLE
Module not found: Error: Can't resolve 'pointer-trap'

### ISSUE THREAD

**Issue by rahuldeo2047** [spiderworm/rocket-riders#1]
Module not found: Error: Can't resolve 'pointer-trap'

Platform:

>Linux multiverse 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Log: 

> me@multiverse:~/THREEJS/rocket-riders$ webpack-dev-server
> Project is running at http://localhost:8080/
> webpack output is served from /
> webpack: wait until bundle finished: /
> Hash: a8d48b3f03f094362727cfb99c8def3e80de7926
> Version: webpack 2.2.1
> Child
>     Hash: a8d48b3f03f094362727
>     Time: 9393ms
>        Asset     Size  Chunks                    Chunk Names
>     index.js  5.93 MB       0  [emitted]  [big]  main
>     chunk    {0} index.js (main) 2.11 MB [entry] [rendered]
>        [52] ./index.js 25 bytes {0} [built]
>        [53] (webpack)-dev-server/client?http://localhost:8080 4.9 kB {0} [built]
>        [54] ./RocketRidersGame.js 1.08 kB {0} [built]
>        [55] ./client.js 954 bytes {0} [built]
>        [59] ./controls/profiles/StandardControlsProfile.js 1.3 kB {0} [built]
>        [65] ./~/ansi-html/index.js 4.26 kB {0} [built]
>       [105] ./~/punycode/punycode.js 14.7 kB {0} [built]
>       [137] ./~/strip-ansi/index.js 161 bytes {0} [built]
>       [141] ./~/url/url.js 23.3 kB {0} [built]
>       [143] (webpack)-dev-server/client/overlay.js 3.59 kB {0} [built]
>       [144] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
>       [146] (webpack)/hot/emitter.js 77 bytes {0} [built]
>       [163] ./view/ViewSystem.js 1.96 kB {0} [built]
>       [165] ./view/cameras/ArenaCamera.js 157 bytes {0} [built]
>       [167] multi (webpack)-dev-server/client?http://localhost:8080 ./index.js 40 bytes {0} [built]
>          + 153 hidden modules
>     
>     ERROR in ./controls/gameInput.js
>     Module not found: Error: Can't resolve 'pointer-trap' in '/home/me/THREEJS/rocket-riders/controls'
>      @ ./controls/gameInput.js 4:18-41
>      @ ./controls/ControlsSystem.js
>      @ ./client.js
>      @ ./index.js
>      @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js
> Child
>     Hash: cfb99c8def3e80de7926
>     Time: 7737ms
>                               Asset     Size  Chunks                    Chunk Names
>     ./demos/standardControlsDemo.js  5.94 MB       0  [emitted]  [big]  standardControlsDemo
>         ./demos/arenaPhysicsDemo.js  5.93 MB       1  [emitted]  [big]  arenaPhysicsDemo
>                     ./demos/test.js  5.71 MB       2  [emitted]  [big]  test
>     chunk    {0} ./demos/standardControlsDemo.js (standardControlsDemo) 2.11 MB [entry] [rendered]
>         [5] ./~/decs/index.js 249 bytes {0} {1} {2} [built]
>        [11] ./PhysicalEntity.js 543 bytes {0} {1} {2} [built]
>        [14] ./shapes/Sphere.js 291 bytes {0} {1} {2} [built]
>        [19] ./shapes/Box.js 277 bytes {0} {1} {2} [built]
>        [48] (webpack)-dev-server/client?http://localhost:8080 4.9 kB {0} {1} {2} [built]
>       [106] ./~/url/url.js 23.3 kB {0} {1} {2} [built]
>       [108] (webpack)-dev-server/client/overlay.js 3.59 kB {0} {1} {2} [built]
>       [109] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} {2} [built]
>       [111] (webpack)/hot/emitter.js 77 bytes {0} {1} {2} [built]
>       [122] ./view/ViewSystem.js 1.96 kB {0} {1} {2} [built]
>       [133] ./levels/StandardArena.js 677 bytes {0} {1} [built]
>       [164] ./demos/standardControlsDemo.js 309 bytes {0} [built]
>       [167] ./controls/profiles/StandardControlsProfile.js 1.3 kB {0} [built]
>       [168] ./demos/base-demos/ControlsDemo.js 1.8 kB {0} [built]
>       [173] multi (webpack)-dev-server/client?http://localhost:8080 ./demos/standardControlsDemo.js 40 bytes {0} [built]
>          + 154 hidden modules
>     chunk    {1} ./demos/arenaPhysicsDemo.js (arenaPhysicsDemo) 2.11 MB [entry] [rendered]
>         [5] ./~/decs/index.js 249 bytes {0} {1} {2} [built]
>        [11] ./PhysicalEntity.js 543 bytes {0} {1} {2} [built]
>        [14] ./shapes/Sphere.js 291 bytes {0} {1} {2} [built]
>        [48] (webpack)-dev-server/client?http://localhost:8080 4.9 kB {0} {1} {2} [built]
>       [102] ./~/strip-ansi/index.js 161 bytes {0} {1} {2} [built]
>       [106] ./~/url/url.js 23.3 kB {0} {1} {2} [built]
>       [108] (webpack)-dev-server/client/overlay.js 3.59 kB {0} {1} {2} [built]
>       [109] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} {2} [built]
>       [111] (webpack)/hot/emitter.js 77 bytes {0} {1} {2} [built]
>       [115] ./physics/PhysicsSystem.js 4.81 kB {0} {1} {2} [built]
>       [122] ./view/ViewSystem.js 1.96 kB {0} {1} {2} [built]
>       [133] ./levels/StandardArena.js 677 bytes {0} {1} [built]
>       [163] ./demos/arenaPhysicsDemo.js 1.93 kB {1} [built]
>       [169] ./demos/demo-entities/Ball.js 305 bytes {1} [built]
>       [172] multi (webpack)-dev-server/client?http://localhost:8080 ./demos/arenaPhysicsDemo.js 40 bytes {1} [built]
>          + 152 hidden modules
>     chunk    {2} ./demos/test.js (test) 2.05 MB [entry] [rendered]
>         [5] ./~/decs/index.js 249 bytes {0} {1} {2} [built]
>        [11] ./PhysicalEntity.js 543 bytes {0} {1} {2} [built]
>        [14] ./shapes/Sphere.js 291 bytes {0} {1} {2} [built]
>        [18] ./shapes/Shape.js 552 bytes {0} {1} {2} [built]
>        [19] ./shapes/Box.js 277 bytes {0} {1} {2} [built]
>        [48] (webpack)-dev-server/client?http://localhost:8080 4.9 kB {0} {1} {2} [built]
>       [102] ./~/strip-ansi/index.js 161 bytes {0} {1} {2} [built]
>       [106] ./~/url/url.js 23.3 kB {0} {1} {2} [built]
>       [108] (webpack)-dev-server/client/overlay.js 3.59 kB {0} {1} {2} [built]
>       [109] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} {2} [built]
>       [111] (webpack)/hot/emitter.js 77 bytes {0} {1} {2} [built]
>       [115] ./physics/PhysicsSystem.js 4.81 kB {0} {1} {2} [built]
>       [122] ./view/ViewSystem.js 1.96 kB {0} {1} {2} [built]
>       [165] ./demos/test.js 1.29 kB {2} [built]
>       [174] multi (webpack)-dev-server/client?http://localhost:8080 ./demos/test.js 40 bytes {2} [built]
>          + 113 hidden modules
>     
>     ERROR in ./controls/gameInput.js
>     Module not found: Error: Can't resolve 'pointer-trap' in '/home/me/THREEJS/rocket-riders/controls'
>      @ ./controls/gameInput.js 4:18-41
>      @ ./controls/ControlsSystem.js
>      @ ./demos/base-demos/StandardDemo.js
>      @ ./demos/arenaPhysicsDemo.js
>      @ multi (webpack)-dev-server/client?http://localhost:8080 ./demos/arenaPhysicsDemo.js
> webpack: Failed to compile.
>

**Comment by spiderworm** [comment]
Fixed!
